Clayton/migrate/vite react
Clayton0024/Auto-Bar pull request #16
Opened 2024-01-31 06:48 UTC by Clayton0024

Migration to vite & react for front end.

2024-02-01 04:59 UTC, brha8286 requested changes

2024-02-01 04:59 UTC, brha8286 commented on Frontend/README.md
> +npm run serve (serving the production build locally)
+ `npm run lint`

2024-02-01 04:59 UTC, brha8286 commented on Frontend/src/App.jsx
> +        <a href="https://react.dev" target="_blank">
Fails lint

2024-02-01 04:59 UTC, brha8286 commented on Frontend/README.md
> +npm  install
Include required versions of node, npm, react, etc.

2024-02-01 15:41 UTC, Clayton0024 commented on Frontend/README.md
> +npm run serve (serving the production build locally)
updated

2024-02-01 15:41 UTC, Clayton0024 commented on Frontend/src/App.jsx
> +        <a href="https://react.dev" target="_blank">
removed that return and made return basic element as it gets overwritten later.

2024-02-08 03:12 UTC, brha8286 commented on Frontend/src/App.jsx
> +      <p>Hello World</p>
perfect

2024-02-08 03:12 UTC, brha8286 approved these changes

2024-02-09 01:53 UTC, merged